### PR TITLE
Better way to install bundler in debian systems

### PR DESCRIPTION
**Pull request by guysoft**
The apt-get package seems not to work

### CODE REVIEW

**Comment by kochd** [comment]
Sorry wont merge as there is no response from the author

**Comment by kochd** [comment]
Close

**Comment by guysoft** [comment]
@kochd Who is the author? [You are the author of the entire repo](https://github.com/kochd/electricsheep-hd-client/graphs/contributors), and there are no headers with authorship in the source. If there is another author then its not surprising he/she wont respond if they don't know about the pull request.

**Comment by kochd** [comment]
Sorry @guysoft for the confusion. My comment on your PR was pending since moths. I was not aware that there is such a thing as pending comments.

**Comment by guysoft** [comment]
If iI remember,  adding sudo gem screwed all my permissions. I pasted exactly what worked here.

**Comment by kochd** [comment]
`gem install` expects at least a gem name

<code>
#gem install
ERROR:  While executing gem ... (Gem::CommandLineError)
    Please specify at least one gem name (e.g. gem build GEMNAME)
</code>

**Comment by guysoft** [comment]
Probably right. Make it
``gem install bundler`` then

**Pull request closed without merging**
